export const PROJECT_COLORS = [
  { label: 'Berry Red', value: '#b8255f' },
  { label: 'Red', value: '#db4035' },
  { label: 'Orange', value: '#ff9933' },
  { label: 'Yellow', value: '#fad000' },
  { label: 'Olive Green', value: '#afb83b' },
  { label: 'Lime Green', value: '#7ecc49' },
  { label: 'Green', value: '#299438' },
  { label: 'Mint Green', value: '#6accbc' },
  { label: 'Teal', value: '#158fad' },
  { label: 'Sky Blue', value: '#14aaf5' },
  { label: 'Light Blue', value: '#96c3eb' },
  { label: 'Blue', value: '#4073ff' },
  { label: 'Grape', value: '#884dff' },
  { label: 'Violet', value: '#af38eb' },
  { label: 'Lavender', value: '#eb96eb' },
  { label: 'Magenta', value: '#e05194' },
  { label: 'Salmon', value: '#ff8d85' },
  { label: 'Charcoal', value: '#808080' },
  { label: 'Grey', value: '#b8b8b8' },
  { label: 'Taupe', value: '#ccac93' },
];
